# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-operator
  labels:
    control-plane: elastic-operator
    k8s-app: elastic-operator
spec:
  selector:
    matchLabels:
      control-plane: elastic-operator
      k8s-app: elastic-operator
  serviceName: elastic-operator
  template:
    metadata:
      labels:
        control-plane: elastic-operator
        k8s-app: elastic-operator
    spec:
      serviceAccountName: elastic-operator
      containers:
      - image: docker.elastic.co/eck/eck-operator:latest
        name: manager
        args: ["manager", "--operator-roles", "all", "--enable-debug-logs=false"]
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEBHOOK_SECRET
          value: webhook-server-secret
        - name: WEBHOOK_PODS_LABEL
          value: elastic-operator
        # - name: OPERATOR_IMAGE
        #   value: docker.elastic.co/eck/eck-operator:latest
        resources:
          limits:
            cpu: 1
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-secret