---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: falco
  namespace: security
  labels:
    app: falco
    role: security
subjects:
  - kind: ServiceAccount
    name: falco
    namespace: security
roleRef:
  kind: ClusterRole
  name: falco
  apiGroup: rbac.authorization.k8s.io
