# Copyright (C) 2019 Skale-5 <ops@skale-5.com>
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: falco
  labels:
    app: falco
spec:
  privileged: true
  hostNetwork: true
  allowedCapabilities: ['*']
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes: ['*']
