apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane
  labels:
    app: crossplane
    app.kubernetes.io/component: crossplane
    app.kubernetes.io/instance: crossplane
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/version: v0.9.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane
subjects:
- kind: ServiceAccount
  name: crossplane
  namespace: crossplane-system
