apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-admin
  labels:
    app: crossplane
    app.kubernetes.io/component: crossplane
    app.kubernetes.io/instance: crossplane
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/version: v0.11.0
    crossplane.io/scope: "system"
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.crossplane.io/aggregate-to-crossplane-admin: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane:system:aggregate-to-crossplane-admin
  labels:
    app: crossplane
    app.kubernetes.io/component: crossplane
    app.kubernetes.io/instance: crossplane
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/version: v0.11.0
    crossplane.io/scope: "system"
    rbac.crossplane.io/aggregate-to-crossplane-admin: "true"
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: crossplane
    app.kubernetes.io/component: crossplane
    app.kubernetes.io/instance: crossplane
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/version: v0.11.0
  name: crossplane-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: crossplane:masters
