apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane
  labels:
    app: crossplane
    app.kubernetes.io/component: crossplane
    app.kubernetes.io/instance: crossplane
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/version: v0.11.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crossplane
      app.kubernetes.io/component: crossplane
      app.kubernetes.io/instance: crossplane
      app.kubernetes.io/name: crossplane
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crossplane
        app.kubernetes.io/component: crossplane
        app.kubernetes.io/instance: crossplane
        app.kubernetes.io/name: crossplane
    spec:
      serviceAccountName: crossplane
      containers:
      - image: crossplane/crossplane:v0.11.0
        args:
        - --debug
        imagePullPolicy: Always
        name: crossplane
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
