# the stack manager ClusterRoleBinding is to the cluster-admin ClusterRole because it needs to
# create arbitrary RBAC permissions for arbitrary stacks.  A service account cannot grant RBAC
# permissions that it doesn't already have itself, so to support the arbitrary permissions needs of
# all stacks, we are using the cluster-admin role.
#
# Note that this is scoped to just the stack manager and not to all of Crossplane (which uses a
# separate service account and role/binding).
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-stack-manager
  labels:
    app: crossplane
    app.kubernetes.io/component: crossplane
    app.kubernetes.io/instance: crossplane
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/version: v0.9.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: stack-manager
  namespace: crossplane-system
