# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: redis
  labels:
    k8s-app: prometheus
    prometheus: k8s
    role: alert-rules
spec:
  groups:
  - name: RedisAlerts
    rules:

    - alert: RedisDown
      expr: redis_up == 0
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Redis down (instance {{ $labels.instance }})"
        message: "Redis instance is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: OutOfMemory
      expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 90
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Out of memory (instance {{ $labels.instance }})"
        message: "Redis is running out of memory (> 90%)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: ReplicationBroken
      expr: delta(redis_connected_slaves[1m]) < 0
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Replication broken (instance {{ $labels.instance }})"
        message: "Redis instance lost a slave\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: TooManyConnections
      expr: redis_connected_clients > 100
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Too many connections (instance {{ $labels.instance }})"
        message: "Redis instance has too many connections\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: NotEnoughConnections
      expr: redis_connected_clients < 5
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Not enough connections (instance {{ $labels.instance }})"
        message: "Redis instance should have more connections (> 5)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: RejectedConnections
      expr: increase(redis_rejected_connections_total[1m]) > 0
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Rejected connections (instance {{ $labels.instance }})"
        message: "Some connections to Redis has been rejected\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"