# Copyright (C) 2019 Nicolas Lamirault <ops@jarvis.com>
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base

namespace: magtape-system

configMapGenerator:
- name: magtape-env
  envs:
  - config/magtape.env
