# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: elasticsearch
  labels:
    k8s-app: prometheus
    prometheus: k8s
    role: alert-rules
spec:
  groups:
  - name: ElasticsearchAlerts
    rules:
    - alert: ElasticHeapUsageTooHigh
      expr: (elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"}) * 100 > 90
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Elastic Heap Usage Too High (instance {{ $labels.instance }})"
        message: "The heap usage is over 90% for 5m\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: ElasticHeapUsageWarning
      expr: (elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"}) * 100 > 80
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Elastic Heap Usage warning (instance {{ $labels.instance }})"
        message: "The heap usage is over 80% for 5m\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: ElasticClusterRed
      expr: elasticsearch_cluster_health_status{color="red"} == 1
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Elastic Cluster Red (instance {{ $labels.instance }})"
        message: "Elastic Cluster Red status\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: NumberOfElasticHealthyNodes
      expr: elasticsearch_cluster_health_number_of_nodes < number_of_nodes
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Number of Elastic Healthy Nodes (instance {{ $labels.instance }})"
        message: "Number Healthy Nodes less then number_of_nodes\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: NumberOfElasticHealthyDataNodes
      expr: elasticsearch_cluster_health_number_of_data_nodes < number_of_data_nodes
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Number of Elastic Healthy Data Nodes (instance {{ $labels.instance }})"
        message: "Number Healthy Data Nodes less then number_of_data_nodes\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: NumberOfRelocationShards
      expr: elasticsearch_cluster_health_relocating_shards > 0
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Number of relocation shards (instance {{ $labels.instance }})"
        message: "Number of relocation shards for 20 min\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: NumberOfInitializingShards
      expr: elasticsearch_cluster_health_initializing_shards > 0
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Number of initializing shards (instance {{ $labels.instance }})"
        message: "Number of initializing shards for 10 min\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: NumberOfUnassignedShards
      expr: elasticsearch_cluster_health_unassigned_shards > 0
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Number of unassigned shards (instance {{ $labels.instance }})"
        message: "Number of unassigned shards for 2 min\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: NumberOfPendingTasks
      expr: elasticsearch_cluster_health_number_of_pending_tasks > 0
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Number of pending tasks (instance {{ $labels.instance }})"
        message: "Number of pending tasks for 10 min. Cluster works slowly.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: ElasticNoNewDocuments
      expr: rate(elasticsearch_indices_docs{es_master_node="false"}[10m]) < 1
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Elastic no new documents (instance {{ $labels.instance }})"
        message: "No new documents for 10 min!\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"