# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
# commonLabels:
#   app.kubernetes.io/manufacturer: jarvis
namespace: logging
resources:
- apmServers.yaml
- elasticSearches.yaml
- kibanas.yaml
- trustedRelationships.yaml
