# Copyright (C) 2016-2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: thanos-querier
  name: thanos-querier
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      component: thanos-querier
  template:
    metadata:
      labels:
        component: thanos-querier
    spec:
      containers:
      - args:
        - query
        - --query.replica-label=replica
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --store=dnssrv+_grpc._tcp.thanos-store.monitoring.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.thanos-receive.monitoring.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.prometheus-k8s.monitoring.svc.cluster.local
        image: quay.io/thanos/thanos:latest
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
        name: thanos-querier
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 9090
          name: http
        readinessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
