# Copyright (C) 2019 Skale-5 <ops@skale-5.com>
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: thanos-store
  name: thanos-store
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  selector:
    component: thanos-store
