# Copyright (C) 2019 Skale-5 <ops@skale-5.com>
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: thanos-compactor
  name: thanos-compactor
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 10902
    targetPort: http
  selector:
    component: thanos-compactor
