# Copyright (C) 2019 Skale-5 <ops@skale-5.com>
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../../base
namespace: monitoring
# commonLabels:
#   app.kubernetes.io/name: thanos
#   app.kubernetes.io/instance: thanos-minotor
#   app.kubernetes.io/version: v0.7.0-rc0
#   app.kubernetes.io/component: monitoring
#   app.kubernetes.io/part-of: skale-5-kubernetes
#   app.kubernetes.io/managed-by: kustomize
#   env: staging
images:
- name: quay.io/thanos/thanos:latest
  newName: quay.io/thanos/thanos
  newTag: v0.7.0
