# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../../base
namespace: logging
# commonLabels:
#   app.kubernetes.io/name: filebeat
#   app.kubernetes.io/instance: filebeat
#   app.kubernetes.io/version: v7.2.0
#   app.kubernetes.io/component: logging
#   app.kubernetes.io/part-of: kubernetes
#   app.kubernetes.io/managed-by: kustomize
#   env: staging
configMapGenerator:
- name: filebeat
  files:
  - filebeat.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    k8s-app: filebeat
