# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- "../../base"
commonLabels:
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/instance: ingress-nginx
  app.kubernetes.io/component: ingress-controller
  app.kubernetes.io/version: v0.25.1
  app.kubernetes.io/part-of: kubernetes
  app.kubernetes.io/managed-by: kustomize
  env: staging
patches:
- patch-service.yaml
images:
- name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:latest
  newName: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
  newTag: 0.21.0
  # newTag: 0.25.1