# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
- op: replace
  path: /spec/version
  value: 7.4.0
- op: replace
  path: /spec/nodes/0/nodeCount
  value: 1
- op: replace
  path: /spec/nodes/0/volumeClaimTemplates/0/spec/resources/requests/storage
  value: 10Gi
- op: replace
  path: /spec/nodes/0/podTemplate/spec/containers/0/env
  value:
    - name: ES_JAVA_OPTS
      value: "-Xms4g -Xmx4g"
- op: replace
  path: /spec/nodes/0/podTemplate/spec/containers/0/resources
  value:
    requests:
      memory: 4Gi
      cpu: 500m
    limits:
      memory: 5Gi
      cpu: 1000m