# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  labels:
    k8s-app: ingress-nginx
data:
  body-size: "20m"