# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ingress-nginx
  labels:
    k8s-app: ingress-nginx
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: ingress-nginx
