# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ingress-nginx
  name: ingress-nginx
spec:
  endpoints:
  - interval: 30s
    port: metrics
    path: /metrics
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: ingress-nginx
