# Copyright (C) 2016, 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-resource-report
  labels:
    k8s-app: kube-resource-report
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kube-resource-report
  template:
    metadata:
      labels:
        k8s-app: kube-resource-report
    spec:
      serviceAccount: kube-resource-report
      containers:
      - name: kube-resource-report
        image: hjacobs/kube-resource-report:latest
        args:
        - --update-interval-minutes=1
        - "--pricing-file=/pricing-file/pricing.csv"
        - /output
        volumeMounts:
        - mountPath: /output
          name: report-data
        - mountPath: /pricing-file/
          name: pricing-file
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: report-data
          readOnly: true
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 20Mi
      volumes:
      - name: report-data
        emptyDir:
          sizeLimit: 500Mi
      - name: pricing-file
        configMap:
          name: pricing-file