# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/manufacturer: jarvis
namespace: logging
resources:
- serviceAccount.yaml
- role.yaml
- roleBinding.yaml
- clusterRole.yaml
- clusterRoleBinding.yaml
- psp.yaml
- deployment.yaml
- service.yaml
- serviceMonitor.yaml
configMapGenerator:
- name: promtail
  files:
  - config/promtail.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    k8s-app: promtail
