# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: promtail
  name: promtail
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: promtail
