# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: monitoring
# commonLabels:
#   app.kubernetes.io/manufacturer: jarvis
resources:
- 0crd-alertmanager.yaml
- 0crd-prometheus.yaml
- 0crd-rule.yaml
- 0crd-serviceMonitor.yaml