# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels:
    k8s-app: pushgateway
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    k8s-app: pushgateway
  type: ClusterIP
