# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: pushgateway
  name: pushgateway
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      k8s-app: pushgateway
