# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../../base
namespace: logging
# commonLabels:
#   app.kubernetes.io/name: elastic-operator
#   app.kubernetes.io/instance: elastic-operator-jarvis
#   app.kubernetes.io/version: v0.9.0
#   app.kubernetes.io/component: logging
#   app.kubernetes.io/part-of: kubernetes
#   app.kubernetes.io/managed-by: kustomize
#   env: staging
