# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
namespace: monitoring
# commonLabels:
#   app.kubernetes.io/name: pushgateway
#   app.kubernetes.io/instance: pushgateway
#   app.kubernetes.io/version: v0.9.1
#   app.kubernetes.io/component: monitoring
#   app.kubernetes.io/part-of: kubernetes
#   app.kubernetes.io/managed-by: kustomize
#   env: staging
images:
- name: prom/pushgateway:latest
  newName: prom/pushgateway
  newTag: v0.9.1