# Copyright (C) 2016, 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
# commonLabels:
#   app.kubernetes.io/manufacturer: jarvis
namespace: monitoring
resources:
- rules/deadmanswitch.yaml
- rules/k8s.yaml
- rules/kube-prometheus-node.yaml
- rules/kubernetes-absent.yaml
- rules/kubernetes-apps.yaml
- rules/kubernetes-resources.yaml
- rules/kubernetes-storage.yaml
- rules/kubernetes-system.yaml
- rules/node-network.yaml
- rules/node.yaml
- rules/prometheus.yaml
- service-account.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- role.yaml
- role-binding.yaml
- deployment.yaml
- service.yaml
- service-monitor.yaml
