# Copyright (C) 2019 Nicolas Lamirault <nicolas.lamirault@gmail.com>
---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
namespace: logging
commonLabels:
  app.kubernetes.io/name: promtail
  app.kubernetes.io/instance: promtail-jarvis
  app.kubernetes.io/version: v0.3.0
  app.kubernetes.io/component: logging
  app.kubernetes.io/part-of: kubernetes
  app.kubernetes.io/managed-by: kustomize
  env: staging
images:
- name: grafana/promtail:latest
  newName: grafana/promtail
  newTag: v0.3.0
